version: '3.8'

services:
  service:
    image: ubuntu:22.04
    container_name: service_container
    command: ["bash"]
    networks:
      - mynetwork

  client:
    image: ubuntu:22.04
    container_name: client_container
    command: ["bash"]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
